import type { LanguageId } from "@/types/language";

export type DeckLanguageId = Exclude<LanguageId, "en-US">;

export interface LanguageDiagnosticWord {
  text: string;
  ipa: string;
  targetUnitSlug: string;
  stressText?: string;
}

export interface LanguageContrastItem {
  left: string;
  right: string;
  ipa: string;
  targetUnitSlug: string;
  focus: string;
}

export interface LanguageSentenceItem {
  text: string;
  ipaHint: string;
  targetUnitSlugs: string[];
  focus: string;
  stressText?: string;
}

export interface LanguageLearningDeck {
  languageId: DeckLanguageId;
  sourceRefs: string[];
  diagnosticWords: LanguageDiagnosticWord[];
  diagnosticPassage: {
    title: string;
    text: string;
    stressText?: string;
    targetUnitSlugs: string[];
  };
  contrastDeck: LanguageContrastItem[];
  sentenceDeck: LanguageSentenceItem[];
}

export const LANGUAGE_LEARNING_DECKS: Record<DeckLanguageId, LanguageLearningDeck> = {
  "es-ES": {
    languageId: "es-ES",
    sourceRefs: [
      "easypronunciation-es-ipa",
      "ipatics-es-ipa",
      "spanishdict-pronunciation",
      "sounds-of-speech-es",
    ],
    diagnosticWords: [
      { text: "casa", ipa: "/ˈkasa/", targetUnitSlug: "es-a" },
      { text: "mesa", ipa: "/ˈmesa/", targetUnitSlug: "es-e" },
      { text: "sí", ipa: "/si/", targetUnitSlug: "es-i" },
      { text: "ocho", ipa: "/ˈotʃo/", targetUnitSlug: "es-o" },
      { text: "luna", ipa: "/ˈluna/", targetUnitSlug: "es-u" },
      { text: "pero", ipa: "/ˈpeɾo/", targetUnitSlug: "es-tap-r" },
      { text: "perro", ipa: "/ˈpero/", targetUnitSlug: "es-trill-r" },
      { text: "jamón", ipa: "/xaˈmon/", targetUnitSlug: "es-x" },
      { text: "niño", ipa: "/ˈniɲo/", targetUnitSlug: "es-ny" },
      { text: "zapato", ipa: "/θaˈpato/", targetUnitSlug: "es-theta" },
      { text: "vida", ipa: "/ˈbiða/", targetUnitSlug: "es-bv" },
      { text: "dedo", ipa: "/ˈdeðo/", targetUnitSlug: "es-d" },
      { text: "agua", ipa: "/ˈaɣwa/", targetUnitSlug: "es-g" },
      { text: "sol", ipa: "/sol/", targetUnitSlug: "es-s" },
      { text: "chico", ipa: "/ˈtʃiko/", targetUnitSlug: "es-ch" },
      { text: "yo", ipa: "/ʝo/", targetUnitSlug: "es-y-ll" },
      { text: "hola", ipa: "/ˈola/", targetUnitSlug: "es-l" },
      { text: "un gato", ipa: "/uŋ ˈgato/", targetUnitSlug: "es-nasal-place" },
      { text: "tierra", ipa: "/ˈtjera/", targetUnitSlug: "es-diphthongs-j" },
      { text: "bueno", ipa: "/ˈbweno/", targetUnitSlug: "es-diphthongs-w" },
      { text: "papá", ipa: "/paˈpa/", targetUnitSlug: "es-lexical-stress" },
      { text: "Buenos días", ipa: "/ˈbwenos ˈdias/", targetUnitSlug: "es-syllable-rhythm" },
    ],
    diagnosticPassage: {
      title: "纯元音、r/rr 和 es-ES /θ/ 筛查",
      text: "Mi perro corre por la plaza. La niña compra pan, queso y zumo por la mañana.",
      targetUnitSlugs: ["es-a", "es-e", "es-tap-r", "es-trill-r", "es-theta"],
    },
    contrastDeck: [
      {
        left: "pero",
        right: "perro",
        ipa: "/ˈpeɾo/ ~ /ˈpero/",
        targetUnitSlug: "es-trill-r",
        focus: "单击 r 与颤音 rr",
      },
      {
        left: "casa",
        right: "caza",
        ipa: "/ˈkasa/ ~ /ˈkaθa/",
        targetUnitSlug: "es-theta",
        focus: "es-ES /s/ 与 /θ/",
      },
      {
        left: "caro",
        right: "carro",
        ipa: "/ˈkaɾo/ ~ /ˈkaro/",
        targetUnitSlug: "es-trill-r",
        focus: "词中 r/rr",
      },
      {
        left: "bebo",
        right: "vivo",
        ipa: "/ˈbeβo/ ~ /ˈbiβo/",
        targetUnitSlug: "es-bv",
        focus: "b/v 不按英语 /v/ 分裂",
      },
      {
        left: "si",
        right: "sí",
        ipa: "/si/ ~ /si/",
        targetUnitSlug: "es-i",
        focus: "短、纯 /i/，不拖长",
      },
      {
        left: "ano",
        right: "año",
        ipa: "/ˈano/ ~ /ˈaɲo/",
        targetUnitSlug: "es-ny",
        focus: "/n/ 与 /ɲ/",
      },
      {
        left: "gato",
        right: "agua",
        ipa: "/ˈgato/ ~ /ˈaɣwa/",
        targetUnitSlug: "es-g",
        focus: "词首 /g/ 与元音间 /ɣ/",
      },
      {
        left: "dedo",
        right: "nada",
        ipa: "/ˈdeðo/ ~ /ˈnaða/",
        targetUnitSlug: "es-d",
        focus: "d 的硬起音与元音间近音",
      },
      {
        left: "chico",
        right: "ciclo",
        ipa: "/ˈtʃiko/ ~ /ˈθiklo/",
        targetUnitSlug: "es-ch",
        focus: "/tʃ/ 和 es-ES /θ/ 的区别",
      },
      {
        left: "llama",
        right: "yema",
        ipa: "/ˈʝama/ ~ /ˈʝema/",
        targetUnitSlug: "es-y-ll",
        focus: "y/ll yeísmo，说明方言变体",
      },
      {
        left: "lata",
        right: "rata",
        ipa: "/ˈlata/ ~ /ˈrata/",
        targetUnitSlug: "es-l",
        focus: "清晰 /l/ vs 颤音 /r/",
      },
      {
        left: "un beso",
        right: "un gato",
        ipa: "/um ˈbeso/ ~ /uŋ ˈgato/",
        targetUnitSlug: "es-nasal-place",
        focus: "鼻音随后接辅音改变位置",
      },
      {
        left: "bien",
        right: "ven",
        ipa: "/bjen/ ~ /ben/",
        targetUnitSlug: "es-diphthongs-j",
        focus: "ie 的 /j/ glide",
      },
      {
        left: "bueno",
        right: "bono",
        ipa: "/ˈbweno/ ~ /ˈbono/",
        targetUnitSlug: "es-diphthongs-w",
        focus: "ue 的 /w/ glide",
      },
      {
        left: "papa",
        right: "papá",
        ipa: "/ˈpapa/ ~ /paˈpa/",
        targetUnitSlug: "es-lexical-stress",
        focus: "词重音改变词义",
      },
      {
        left: "hablo",
        right: "habló",
        ipa: "/ˈaβlo/ ~ /aˈβlo/",
        targetUnitSlug: "es-lexical-stress",
        focus: "accent mark 和重音位置",
      },
    ],
    sentenceDeck: [
      {
        text: "La casa está cerca de la plaza.",
        ipaHint: "/a e θ/",
        targetUnitSlugs: ["es-a", "es-e", "es-theta"],
        focus: "纯元音和 es-ES /θ/",
      },
      {
        text: "Pero mi perro corre rápido.",
        ipaHint: "/ɾ r/",
        targetUnitSlugs: ["es-tap-r", "es-trill-r"],
        focus: "r/rr 对比",
      },
      {
        text: "El niño bebe agua fría.",
        ipaHint: "/ɲ β/",
        targetUnitSlugs: ["es-ny", "es-bv"],
        focus: "ñ 与 b/v 近音",
      },
      {
        text: "Javier trabaja por la mañana.",
        ipaHint: "/x a/",
        targetUnitSlugs: ["es-x", "es-a"],
        focus: "西语 /x/ 和纯 /a/",
      },
      {
        text: "Cinco zapatos son azules.",
        ipaHint: "/θ s/",
        targetUnitSlugs: ["es-theta"],
        focus: "Castilian c/z",
      },
      {
        text: "Una familia vive en Madrid.",
        ipaHint: "/u i ð/",
        targetUnitSlugs: ["es-u", "es-i", "es-d"],
        focus: "短元音和 /ð/",
      },
      {
        text: "Chico, escucha la leche.",
        ipaHint: "/tʃ/",
        targetUnitSlugs: ["es-ch", "es-e"],
        focus: "ch /tʃ/",
      },
      {
        text: "Yo llevo la llave amarilla.",
        ipaHint: "/ʝ/",
        targetUnitSlugs: ["es-y-ll"],
        focus: "y/ll yeísmo 与方言说明",
      },
      {
        text: "Un gato duerme en un banco.",
        ipaHint: "nasal place",
        targetUnitSlugs: ["es-nasal-place", "es-g"],
        focus: "鼻音位置同化",
      },
      {
        text: "Tierra y cielo son palabras con diptongos.",
        ipaHint: "/j/",
        targetUnitSlugs: ["es-diphthongs-j", "es-theta"],
        focus: "ie/io 等 /j/ glide",
      },
      {
        text: "Bueno, cuatro amigos juegan afuera.",
        ipaHint: "/w ɣ/",
        targetUnitSlugs: ["es-diphthongs-w", "es-g"],
        focus: "ue/ua /w/ glide 和 g 近音",
      },
      {
        text: "Papá habló con el médico.",
        ipaHint: "stress",
        targetUnitSlugs: ["es-lexical-stress"],
        focus: "重音和 accent marks",
      },
      {
        text: "Buenos días, muchas gracias.",
        ipaHint: "syllable rhythm",
        targetUnitSlugs: ["es-syllable-rhythm", "es-diphthongs-w"],
        focus: "西语音节节奏",
      },
      {
        text: "El carro rojo va por la carretera.",
        ipaHint: "/r x ɾ/",
        targetUnitSlugs: ["es-trill-r", "es-x", "es-tap-r"],
        focus: "rr、j、单击 r",
      },
      {
        text: "La ciudad tiene cinco universidades.",
        ipaHint: "/θj s/",
        targetUnitSlugs: ["es-diphthongs-j", "es-theta", "es-s"],
        focus: "es-ES /θ/、/s/ 和 ciudad 的 /j/",
      },
      {
        text: "Mi amigo dice que todo va bien.",
        ipaHint: "/ð ɣ j/",
        targetUnitSlugs: ["es-d", "es-g", "es-diphthongs-j"],
        focus: "d/g 近音和 bien 的 /j/",
      },
    ],
  },
  "fr-FR": {
    languageId: "fr-FR",
    sourceRefs: [
      "easypronunciation-fr-ipa",
      "openipa-fr",
      "lawless-french-ipa",
      "phonetique-ca",
    ],
    diagnosticWords: [
      { text: "si", ipa: "/si/", targetUnitSlug: "fr-i" },
      { text: "tu", ipa: "/ty/", targetUnitSlug: "fr-y" },
      { text: "peu", ipa: "/pø/", targetUnitSlug: "fr-eu-close" },
      { text: "sœur", ipa: "/sœʁ/", targetUnitSlug: "fr-eu-open" },
      { text: "sans", ipa: "/sɑ̃/", targetUnitSlug: "fr-an" },
      { text: "vin", ipa: "/vɛ̃/", targetUnitSlug: "fr-in" },
      { text: "bon", ipa: "/bɔ̃/", targetUnitSlug: "fr-on" },
      { text: "rue", ipa: "/ʁy/", targetUnitSlug: "fr-r" },
      { text: "petit", ipa: "/pəti/", targetUnitSlug: "fr-schwa" },
      { text: "les amis", ipa: "/lez‿ami/", targetUnitSlug: "fr-liaison" },
      { text: "la", ipa: "/la/", targetUnitSlug: "fr-a" },
      { text: "beau", ipa: "/bo/", targetUnitSlug: "fr-o-close" },
      { text: "porte", ipa: "/pɔʁt/", targetUnitSlug: "fr-o-open" },
      { text: "un", ipa: "/œ̃/", targetUnitSlug: "fr-un" },
      { text: "chat", ipa: "/ʃa/", targetUnitSlug: "fr-sh" },
      { text: "jour", ipa: "/ʒuʁ/", targetUnitSlug: "fr-zh" },
      { text: "agneau", ipa: "/aɲo/", targetUnitSlug: "fr-ny" },
      { text: "fille", ipa: "/fij/", targetUnitSlug: "fr-glide-j" },
      { text: "huit", ipa: "/ɥit/", targetUnitSlug: "fr-glide-hui" },
      { text: "oui", ipa: "/wi/", targetUnitSlug: "fr-glide-w" },
    ],
    diagnosticPassage: {
      title: "前圆唇元音、鼻化元音和连诵筛查",
      text: "Un étudiant prend un bon café. Les amis parlent dans une petite rue.",
      targetUnitSlugs: ["fr-y", "fr-an", "fr-in", "fr-on", "fr-liaison"],
    },
    contrastDeck: [
      {
        left: "si",
        right: "su",
        ipa: "/si/ ~ /sy/",
        targetUnitSlug: "fr-y",
        focus: "/i/ 与前圆唇 /y/",
      },
      {
        left: "deux",
        right: "sœur",
        ipa: "/dø/ ~ /sœʁ/",
        targetUnitSlug: "fr-eu-open",
        focus: "/ø/ 与 /œ/",
      },
      {
        left: "sans",
        right: "son",
        ipa: "/sɑ̃/ ~ /sɔ̃/",
        targetUnitSlug: "fr-on",
        focus: "鼻化元音对比",
      },
      {
        left: "vin",
        right: "vent",
        ipa: "/vɛ̃/ ~ /vɑ̃/",
        targetUnitSlug: "fr-in",
        focus: "/ɛ̃/ 与 /ɑ̃/",
      },
      {
        left: "rue",
        right: "lu",
        ipa: "/ʁy/ ~ /ly/",
        targetUnitSlug: "fr-r",
        focus: "法语小舌 /ʁ/",
      },
      {
        left: "les amis",
        right: "les livres",
        ipa: "/lez‿ami/ ~ /le livʁ/",
        targetUnitSlug: "fr-liaison",
        focus: "必要连诵 vs 不连诵",
      },
      {
        left: "la",
        right: "lait",
        ipa: "/la/ ~ /lɛ/",
        targetUnitSlug: "fr-a",
        focus: "/a/ 与 /ɛ/ 开口对比",
      },
      {
        left: "beau",
        right: "bonne",
        ipa: "/bo/ ~ /bɔn/",
        targetUnitSlug: "fr-o-open",
        focus: "/o/ 与 /ɔ/ 对比",
      },
      {
        left: "un",
        right: "in",
        ipa: "/œ̃/ ~ /ɛ̃/",
        targetUnitSlug: "fr-un",
        focus: "/œ̃/ 可与 /ɛ̃/ 合并，按变体提示",
      },
      {
        left: "chat",
        right: "chaud",
        ipa: "/ʃa/ ~ /ʃo/",
        targetUnitSlug: "fr-sh",
        focus: "法语 ch 是 /ʃ/，不是 /tʃ/",
      },
      {
        left: "je",
        right: "chez",
        ipa: "/ʒə/ ~ /ʃe/",
        targetUnitSlug: "fr-zh",
        focus: "/ʒ/ 与 /ʃ/ 清浊对比",
      },
      {
        left: "agneau",
        right: "anneau",
        ipa: "/aɲo/ ~ /ano/",
        targetUnitSlug: "fr-ny",
        focus: "/ɲ/ 不拆成 /n+j/",
      },
      {
        left: "fille",
        right: "fil",
        ipa: "/fij/ ~ /fil/",
        targetUnitSlug: "fr-glide-j",
        focus: "末尾 /j/ glide",
      },
      {
        left: "huit",
        right: "oui",
        ipa: "/ɥit/ ~ /wi/",
        targetUnitSlug: "fr-glide-hui",
        focus: "/ɥ/ 与 /w/ 的圆唇 glide",
      },
      {
        left: "petit",
        right: "ptit",
        ipa: "/pəti/ ~ /pti/",
        targetUnitSlug: "fr-schwa",
        focus: "schwa 是否发出受语速和语境影响",
      },
      {
        left: "petit",
        right: "petite",
        ipa: "/pəti/ ~ /pətit/",
        targetUnitSlug: "fr-final-consonant-silence",
        focus: "孤立阳性词尾静音 vs 派生形式",
      },
    ],
    sentenceDeck: [
      {
        text: "Tu veux du café ?",
        ipaHint: "/y ø/",
        targetUnitSlugs: ["fr-y", "fr-eu-close"],
        focus: "前圆唇元音",
      },
      {
        text: "Un bon vin blanc.",
        ipaHint: "/œ̃ ɔ̃ ɛ̃ ɑ̃/",
        targetUnitSlugs: ["fr-in", "fr-on", "fr-an"],
        focus: "鼻化元音串联",
      },
      {
        text: "Les amis arrivent à Paris.",
        ipaHint: "/z‿a ʁ/",
        targetUnitSlugs: ["fr-liaison", "fr-r"],
        focus: "连诵和法语 r",
      },
      {
        text: "Je prends un petit déjeuner.",
        ipaHint: "/ə ɑ̃/",
        targetUnitSlugs: ["fr-schwa", "fr-an"],
        focus: "schwa 与鼻化",
      },
      {
        text: "La sœur de Luc parle peu.",
        ipaHint: "/œ ø/",
        targetUnitSlugs: ["fr-eu-open", "fr-eu-close"],
        focus: "/œ/ 和 /ø/",
      },
      {
        text: "Il habite avec elle.",
        ipaHint: "enchaînement",
        targetUnitSlugs: ["fr-enchainement"],
        focus: "词尾辅音和连音",
      },
      {
        text: "Le chat jaune dort.",
        ipaHint: "/ʃ ʒ/",
        targetUnitSlugs: ["fr-sh", "fr-zh", "fr-final-consonant-silence"],
        focus: "ch /ʃ/、j /ʒ/ 和词尾静音",
      },
      {
        text: "L’ami arrive à huit heures.",
        ipaHint: "elision + /ɥ/",
        targetUnitSlugs: ["fr-elision", "fr-glide-hui", "fr-enchainement"],
        focus: "省音、enchaînement 和 /ɥ/",
      },
      {
        text: "Une fille lit près de la porte.",
        ipaHint: "/j a ɔ/",
        targetUnitSlugs: ["fr-glide-j", "fr-a", "fr-o-open"],
        focus: "/j/ glide 与 /a ɔ/",
      },
      {
        text: "Oui, nous allons au bureau.",
        ipaHint: "/w o/",
        targetUnitSlugs: ["fr-glide-w", "fr-o-close", "fr-u"],
        focus: "/w/ glide、/o/ 和 /u/",
      },
      {
        text: "Un parfum brun peut varier selon l’accent.",
        ipaHint: "/œ̃ ɛ̃/",
        targetUnitSlugs: ["fr-un", "fr-in", "fr-elision"],
        focus: "/œ̃/ 与 /ɛ̃/ 可能合并，不硬判变体",
      },
      {
        text: "Le grand homme parle encore.",
        ipaHint: "liaison",
        targetUnitSlugs: ["fr-liaison", "fr-r", "fr-an"],
        focus: "grand homme 的 liaison",
      },
      {
        text: "Petit à petit, elle écoute.",
        ipaHint: "/ə/",
        targetUnitSlugs: ["fr-schwa", "fr-enchainement"],
        focus: "schwa 与词间连音",
      },
      {
        text: "Trop grand, trop lent, trop fort.",
        ipaHint: "final silence",
        targetUnitSlugs: ["fr-final-consonant-silence", "fr-an", "fr-r"],
        focus: "词尾静音和法语 r",
      },
      {
        text: "J’aime le bon vin blanc.",
        ipaHint: "elision + nasal vowels",
        targetUnitSlugs: ["fr-elision", "fr-on", "fr-in", "fr-an"],
        focus: "省音和鼻化元音",
      },
      {
        text: "Il y a un agneau près du jardin.",
        ipaHint: "/ɲ j/",
        targetUnitSlugs: ["fr-ny", "fr-glide-j", "fr-un"],
        focus: "/ɲ/、/j/ 和 /œ̃/ 变体",
      },
    ],
  },
  "ru-RU": {
    languageId: "ru-RU",
    sourceRefs: [
      "easypronunciation-ru-ipa",
      "ipatics-ru-ipa",
      "easypronunciation-ru-trainer",
      "wiktionary-ru-pronunciation-appendix",
    ],
    diagnosticWords: [
      { text: "мама", stressText: "ма́ма", ipa: "/ˈmamə/", targetUnitSlug: "ru-a" },
      { text: "город", stressText: "го́род", ipa: "/ˈgorət/", targetUnitSlug: "ru-o" },
      { text: "это", stressText: "э́то", ipa: "/ˈetə/", targetUnitSlug: "ru-e" },
      { text: "мир", ipa: "/mir/", targetUnitSlug: "ru-i" },
      { text: "сыр", ipa: "/sɨr/", targetUnitSlug: "ru-y" },
      { text: "рука", stressText: "рука́", ipa: "/rʊˈka/", targetUnitSlug: "ru-u" },
      { text: "мать", ipa: "/matʲ/", targetUnitSlug: "ru-hard-soft" },
      { text: "день", ipa: "/dʲenʲ/", targetUnitSlug: "ru-soft-t-d" },
      { text: "зима", stressText: "зима́", ipa: "/zʲɪˈma/", targetUnitSlug: "ru-soft-s-z" },
      { text: "люк", ipa: "/lʲuk/", targetUnitSlug: "ru-soft-n-l-r" },
      { text: "пять", ipa: "/pʲatʲ/", targetUnitSlug: "ru-soft-labials" },
      { text: "уголь", stressText: "у́голь", ipa: "/ˈugəlʲ/", targetUnitSlug: "ru-soft-sign" },
      { text: "река", stressText: "река́", ipa: "/rʲɪˈka/", targetUnitSlug: "ru-r" },
      { text: "хорошо", stressText: "хорошо́", ipa: "/xərɐˈʂo/", targetUnitSlug: "ru-x" },
      { text: "журнал", stressText: "журна́л", ipa: "/ʐʊrˈnal/", targetUnitSlug: "ru-sh-zh" },
      { text: "цена", stressText: "цена́", ipa: "/tsɨˈna/", targetUnitSlug: "ru-ts" },
      { text: "чай", ipa: "/tɕaj/", targetUnitSlug: "ru-ch" },
      { text: "щи", ipa: "/ɕːi/", targetUnitSlug: "ru-shch" },
      { text: "йогурт", stressText: "йо́гурт", ipa: "/ˈjogʊrt/", targetUnitSlug: "ru-j" },
      { text: "семья", stressText: "семья́", ipa: "/sʲɪmʲˈja/", targetUnitSlug: "ru-iotated-vowels" },
      { text: "молоко", stressText: "молоко́", ipa: "/məlɐˈko/", targetUnitSlug: "ru-stress-reduction" },
      { text: "Москва", stressText: "Москва́", ipa: "/mɐˈskva/", targetUnitSlug: "ru-unstressed-o-a" },
      { text: "минута", stressText: "мину́та", ipa: "/mʲɪˈnutə/", targetUnitSlug: "ru-unstressed-e-ya" },
      { text: "друг", ipa: "/druk/", targetUnitSlug: "ru-final-devoicing" },
      { text: "встреча", stressText: "встре́ча", ipa: "/ˈfstrʲetɕə/", targetUnitSlug: "ru-voicing-assimilation" },
      { text: "текст", ipa: "/tʲekst/", targetUnitSlug: "ru-clusters" },
    ],
    diagnosticPassage: {
      title: "俄语重音、弱化、硬软辅音、清化和辅音丛筛查",
      text: "Здравствуйте. Сегодня студент идёт в школу, читает русский текст, встречает друга и говорит спасибо.",
      stressText: "Здра́вствуйте. Сего́дня студе́нт идёт в шко́лу, чита́ет ру́сский текст, встреча́ет дру́га и говори́т спаси́бо.",
      targetUnitSlugs: [
        "ru-stress-reduction",
        "ru-unstressed-o-a",
        "ru-unstressed-e-ya",
        "ru-hard-soft",
        "ru-soft-t-d",
        "ru-soft-s-z",
        "ru-ts",
        "ru-ch",
        "ru-final-devoicing",
        "ru-voicing-assimilation",
        "ru-clusters",
      ],
    },
    contrastDeck: [
      { left: "мат", right: "мать", ipa: "/mat/ ~ /matʲ/", targetUnitSlug: "ru-soft-sign", focus: "硬/软辅音和软音符号" },
      { left: "лук", right: "люк", ipa: "/luk/ ~ /lʲuk/", targetUnitSlug: "ru-soft-n-l-r", focus: "л vs ль" },
      { left: "и", right: "ы", ipa: "/i/ ~ /ɨ/", targetUnitSlug: "ru-y", focus: "/i/ 与 /ɨ/" },
      { left: "мэр", right: "мел", ipa: "/mɛr/ ~ /mʲel/", targetUnitSlug: "ru-e", focus: "э/е 与前辅音软化" },
      { left: "ток", right: "тётя", ipa: "/tok/ ~ /ˈtʲotʲə/", targetUnitSlug: "ru-soft-t-d", focus: "硬 т 与软 ть" },
      { left: "сад", right: "сядь", ipa: "/sat/ ~ /sʲatʲ/", targetUnitSlug: "ru-soft-s-z", focus: "硬 с 与软 сь" },
      { left: "пять", right: "пить", ipa: "/pʲatʲ/ ~ /pʲitʲ/", targetUnitSlug: "ru-soft-labials", focus: "软唇音" },
      { left: "шить", right: "жить", ipa: "/ʂɨtʲ/ ~ /ʐɨtʲ/", targetUnitSlug: "ru-sh-zh", focus: "ш/ж 厚而偏硬" },
      { left: "чай", right: "царь", ipa: "/tɕaj/ ~ /tsarʲ/", targetUnitSlug: "ru-ts", focus: "ч 与 ц" },
      { left: "чай", right: "щи", ipa: "/tɕaj/ ~ /ɕːi/", targetUnitSlug: "ru-shch", focus: "ч 与长软 щ" },
      { left: "мой", right: "мир", ipa: "/moj/ ~ /mir/", targetUnitSlug: "ru-j", focus: "й glide 与 /i/" },
      { left: "я", right: "а", ipa: "/ja/ ~ /a/", targetUnitSlug: "ru-iotated-vowels", focus: "iotated vowel 起首 /j/" },
      { left: "дом", right: "дома", ipa: "/dom/ ~ /dɐˈma/", targetUnitSlug: "ru-unstressed-o-a", focus: "重音改变 о/а 质量" },
      { left: "семья", right: "сам", ipa: "/sʲɪmʲˈja/ ~ /sam/", targetUnitSlug: "ru-unstressed-e-ya", focus: "非重读 е/я 弱化和软化" },
      { left: "дуб", right: "дуба", ipa: "/dup/ ~ /duˈba/", targetUnitSlug: "ru-final-devoicing", focus: "词尾清化" },
      { left: "встреча", right: "вес", ipa: "/ˈfstrʲetɕə/ ~ /vʲes/", targetUnitSlug: "ru-voicing-assimilation", focus: "辅音清浊同化" },
      { left: "стол", right: "снег", ipa: "/stol/ ~ /snʲek/", targetUnitSlug: "ru-clusters", focus: "辅音丛不插元音" },
      { left: "река", right: "рука", ipa: "/rʲɪˈka/ ~ /rʊˈka/", targetUnitSlug: "ru-r", focus: "软/硬 r 和元音弱化" },
    ],
    sentenceDeck: [
      { text: "Мама дома.", stressText: "Ма́ма до́ма.", ipaHint: "/ˈmamə ˈdomə/", targetUnitSlugs: ["ru-a", "ru-stress-reduction"], focus: "重音和非重读弱化" },
      { text: "Я люблю русский язык.", stressText: "Я люблю́ ру́сский язы́к.", ipaHint: "/ruskij jɪˈzɨk/", targetUnitSlugs: ["ru-y", "ru-hard-soft", "ru-iotated-vowels"], focus: "/ɨ/、硬软辅音和 iotated vowels" },
      { text: "Здравствуйте, студент.", stressText: "Здра́вствуйте, студе́нт.", ipaHint: "clusters", targetUnitSlugs: ["ru-clusters"], focus: "辅音丛" },
      { text: "Чай и щи горячие.", stressText: "Чай и щи горя́чие.", ipaHint: "/tɕ ɕː/", targetUnitSlugs: ["ru-ch", "ru-shch"], focus: "ч/щ 对比" },
      { text: "Хорошо, спасибо.", stressText: "Хорошо́, спаси́бо.", ipaHint: "/x spɐˈsʲibə/", targetUnitSlugs: ["ru-x", "ru-stress-reduction"], focus: "/x/ 与弱化" },
      { text: "Встреча завтра утром.", stressText: "Встре́ча за́втра у́тром.", ipaHint: "clusters + assimilation", targetUnitSlugs: ["ru-clusters", "ru-voicing-assimilation"], focus: "辅音丛和清浊同化" },
      { text: "Это билет в театр.", stressText: "Э́то биле́т в теа́тр.", ipaHint: "/e/", targetUnitSlugs: ["ru-e", "ru-unstressed-e-ya"], focus: "/e/ 与 е/э" },
      { text: "День и дом звучат по-разному.", stressText: "День и дом звуча́т по-ра́зному.", ipaHint: "/d dʲ/", targetUnitSlugs: ["ru-soft-t-d"], focus: "硬/软 д" },
      { text: "Сад зимой синий.", stressText: "Сад зимо́й си́ний.", ipaHint: "/s sʲ zʲ/", targetUnitSlugs: ["ru-soft-s-z"], focus: "с/з 软化" },
      { text: "Лук и люк - разные слова.", stressText: "Лук и люк - ра́зные слова́.", ipaHint: "/l lʲ/", targetUnitSlugs: ["ru-soft-n-l-r"], focus: "л/ль 对比" },
      { text: "Пять билетов лежат на столе.", stressText: "Пять биле́тов лежа́т на столе́.", ipaHint: "/pʲ bʲ/", targetUnitSlugs: ["ru-soft-labials"], focus: "软唇音" },
      { text: "Уголь лежит у двери.", stressText: "У́голь лежи́т у две́ри.", ipaHint: "/ʲ/", targetUnitSlugs: ["ru-soft-sign"], focus: "软音符号" },
      { text: "Центр улицы рядом.", stressText: "Центр у́лицы ря́дом.", ipaHint: "/ts/", targetUnitSlugs: ["ru-ts"], focus: "ц /ts/" },
      { text: "Мой поезд идёт на юг.", stressText: "Мой по́езд идёт на юг.", ipaHint: "/j/", targetUnitSlugs: ["ru-j", "ru-iotated-vowels"], focus: "й 和 iotated vowels" },
      { text: "Москва сегодня холодная.", stressText: "Москва́ сего́дня хо́лодная.", ipaHint: "/ɐ ə/", targetUnitSlugs: ["ru-unstressed-o-a", "ru-unstressed-e-ya"], focus: "非重读元音弱化" },
      { text: "Друг ждёт у гаража.", stressText: "Друг ждёт у гаража́.", ipaHint: "final devoicing", targetUnitSlugs: ["ru-final-devoicing", "ru-sh-zh"], focus: "词尾清化和 ж/ш" },
      { text: "Сделать быстро трудно.", stressText: "Сде́лать бы́стро тру́дно.", ipaHint: "voicing assimilation", targetUnitSlugs: ["ru-voicing-assimilation", "ru-soft-t-d"], focus: "清浊同化" },
      { text: "Текст простой, но группа большая.", stressText: "Текст просто́й, но гру́ппа больша́я.", ipaHint: "clusters", targetUnitSlugs: ["ru-clusters"], focus: "辅音丛不加元音" },
    ],
  },
};

LANGUAGE_LEARNING_DECKS["ru-RU"] = {
  ...LANGUAGE_LEARNING_DECKS["ru-RU"],
  diagnosticWords: [
    { text: "мама", ipa: "/ˈmamə/", targetUnitSlug: "ru-a", stressText: "ма́ма" },
    { text: "город", ipa: "/ˈgorət/", targetUnitSlug: "ru-o", stressText: "го́род" },
    { text: "это", ipa: "/ˈetə/", targetUnitSlug: "ru-e", stressText: "э́то" },
    { text: "мир", ipa: "/mir/", targetUnitSlug: "ru-i" },
    { text: "сыр", ipa: "/sɨr/", targetUnitSlug: "ru-y" },
    { text: "рука", ipa: "/rʊˈka/", targetUnitSlug: "ru-u", stressText: "рука́" },
    { text: "мать", ipa: "/matʲ/", targetUnitSlug: "ru-hard-soft" },
    { text: "тётя", ipa: "/ˈtʲotʲə/", targetUnitSlug: "ru-soft-t-d" },
    { text: "зима", ipa: "/zʲɪˈma/", targetUnitSlug: "ru-soft-s-z", stressText: "зима́" },
    { text: "люк", ipa: "/lʲuk/", targetUnitSlug: "ru-soft-n-l-r" },
    { text: "билет", ipa: "/bʲɪˈlʲet/", targetUnitSlug: "ru-soft-labials", stressText: "биле́т" },
    { text: "письмо", ipa: "/pʲɪsʲˈmo/", targetUnitSlug: "ru-soft-sign", stressText: "письмо́" },
    { text: "река", ipa: "/rʲɪˈka/", targetUnitSlug: "ru-r", stressText: "река́" },
    { text: "хлеб", ipa: "/xlʲep/", targetUnitSlug: "ru-x" },
    { text: "школа", ipa: "/ˈʂkolə/", targetUnitSlug: "ru-sh-zh", stressText: "шко́ла" },
    { text: "цена", ipa: "/tsɨˈna/", targetUnitSlug: "ru-ts", stressText: "цена́" },
    { text: "чай", ipa: "/tɕaj/", targetUnitSlug: "ru-ch" },
    { text: "щи", ipa: "/ɕːi/", targetUnitSlug: "ru-shch" },
    { text: "язык", ipa: "/jɪˈzɨk/", targetUnitSlug: "ru-j", stressText: "язы́к" },
    { text: "семья", ipa: "/sʲɪmʲˈja/", targetUnitSlug: "ru-iotated-vowels", stressText: "семья́" },
    { text: "спасибо", ipa: "/spɐˈsʲibə/", targetUnitSlug: "ru-stress-reduction", stressText: "спаси́бо" },
    { text: "Москва", ipa: "/mɐˈskva/", targetUnitSlug: "ru-unstressed-o-a", stressText: "Москва́" },
    { text: "сегодня", ipa: "/sʲɪˈvodnʲə/", targetUnitSlug: "ru-unstressed-e-ya", stressText: "сего́дня" },
    { text: "друг", ipa: "/druk/", targetUnitSlug: "ru-final-devoicing" },
    { text: "встреча", ipa: "/ˈfstrʲetɕə/", targetUnitSlug: "ru-voicing-assimilation", stressText: "встре́ча" },
    { text: "здравствуйте", ipa: "/ˈzdrastvʊjtʲe/", targetUnitSlug: "ru-clusters", stressText: "здра́вствуйте" },
  ],
  diagnosticPassage: {
    title: "重音、弱化、硬软辅音和辅音丛筛查",
    text: "Здравствуйте. Сегодня студент идёт в школу, читает русский текст и говорит спасибо.",
    stressText: "Здра́вствуйте. Сего́дня студе́нт идёт в шко́лу, чита́ет ру́сский текст и говори́т спаси́бо.",
    targetUnitSlugs: [
      "ru-stress-reduction",
      "ru-hard-soft",
      "ru-soft-t-d",
      "ru-ch",
      "ru-clusters",
      "ru-unstressed-e-ya",
    ],
  },
  contrastDeck: [
    { left: "мат", right: "мать", ipa: "/mat/ ~ /matʲ/", targetUnitSlug: "ru-soft-sign", focus: "硬辅音 vs 软音符号 ь" },
    { left: "лук", right: "люк", ipa: "/luk/ ~ /lʲuk/", targetUnitSlug: "ru-soft-n-l-r", focus: "л vs ль" },
    { left: "и", right: "ы", ipa: "/i/ ~ /ɨ/", targetUnitSlug: "ru-y", focus: "/i/ 与 /ɨ/" },
    { left: "шить", right: "жить", ipa: "/ʂɨtʲ/ ~ /ʐɨtʲ/", targetUnitSlug: "ru-sh-zh", focus: "ш/ж 后的硬音色" },
    { left: "чай", right: "царь", ipa: "/tɕaj/ ~ /tsarʲ/", targetUnitSlug: "ru-ch", focus: "ч 与 ц" },
    { left: "дом", right: "дома", ipa: "/dom/ ~ /dɐˈma/", targetUnitSlug: "ru-stress-reduction", focus: "重音改变元音质量" },
    { left: "мэр", right: "мел", ipa: "/mɛr/ ~ /mʲel/", targetUnitSlug: "ru-e", focus: "э 不软化前辅音，е 常带软化" },
    { left: "ток", right: "тётя", ipa: "/tok/ ~ /ˈtʲotʲə/", targetUnitSlug: "ru-soft-t-d", focus: "硬 т/d 与软 ть/дь" },
    { left: "сад", right: "сядь", ipa: "/sat/ ~ /sʲatʲ/", targetUnitSlug: "ru-soft-s-z", focus: "硬 с 与软 сь" },
    { left: "пять", right: "пить", ipa: "/pʲatʲ/ ~ /pʲitʲ/", targetUnitSlug: "ru-soft-labials", focus: "唇音软化时舌面也要抬起" },
    { left: "цена", right: "чай", ipa: "/tsɨˈna/ ~ /tɕaj/", targetUnitSlug: "ru-ts", focus: "ц 偏硬，ч 偏软" },
    { left: "чай", right: "щи", ipa: "/tɕaj/ ~ /ɕːi/", targetUnitSlug: "ru-shch", focus: "ч 的塞擦音 vs щ 的长软擦音" },
    { left: "мой", right: "мир", ipa: "/moj/ ~ /mir/", targetUnitSlug: "ru-j", focus: "й 是短 /j/，不要和软化混淆" },
    { left: "я", right: "семья", ipa: "/ja/ ~ /sʲɪmʲˈja/", targetUnitSlug: "ru-iotated-vowels", focus: "я/е/ё/ю 在不同位置触发 /j/ 或软化" },
    { left: "молоко", right: "Москва", ipa: "/məlɐˈko/ ~ /mɐˈskva/", targetUnitSlug: "ru-unstressed-o-a", focus: "非重读 о/а 弱化" },
    { left: "семья", right: "сегодня", ipa: "/sʲɪmʲˈja/ ~ /sʲɪˈvodnʲə/", targetUnitSlug: "ru-unstressed-e-ya", focus: "非重读 е/я 弱化" },
    { left: "друг", right: "друга", ipa: "/druk/ ~ /ˈdrugə/", targetUnitSlug: "ru-final-devoicing", focus: "词尾浊辅音清化" },
    { left: "встреча", right: "вокзал", ipa: "/ˈfstrʲetɕə/ ~ /vɐgˈzal/", targetUnitSlug: "ru-voicing-assimilation", focus: "辅音丛清浊同化" },
    { left: "текст", right: "спорт", ipa: "/tʲekst/ ~ /sport/", targetUnitSlug: "ru-clusters", focus: "辅音丛中不要插入额外元音" },
  ],
  sentenceDeck: [
    { text: "Мама дома.", ipaHint: "/ˈmamə ˈdomə/", targetUnitSlugs: ["ru-a", "ru-unstressed-o-a"], focus: "重音和非重读弱化", stressText: "Ма́ма до́ма." },
    { text: "Я люблю русский язык.", ipaHint: "/ruskij jɪˈzɨk/", targetUnitSlugs: ["ru-y", "ru-soft-labials", "ru-j"], focus: "/ɨ/ 和硬软辅音", stressText: "Я люблю́ ру́сский язы́к." },
    { text: "Здравствуйте, студент.", ipaHint: "clusters", targetUnitSlugs: ["ru-clusters", "ru-soft-t-d"], focus: "辅音丛", stressText: "Здра́вствуйте, студе́нт." },
    { text: "Чай и щи горячие.", ipaHint: "/tɕ ɕː/", targetUnitSlugs: ["ru-ch", "ru-shch", "ru-unstressed-o-a"], focus: "ч/щ 对比", stressText: "Чай и щи горя́чие." },
    { text: "Хорошо, спасибо.", ipaHint: "/x spɐˈsʲibə/", targetUnitSlugs: ["ru-x", "ru-stress-reduction", "ru-soft-s-z"], focus: "/x/ 与弱化", stressText: "Хорошо́, спаси́бо." },
    { text: "Встреча завтра утром.", ipaHint: "clusters + stress", targetUnitSlugs: ["ru-clusters", "ru-voicing-assimilation", "ru-unstressed-o-a"], focus: "辅音丛和词重音", stressText: "Встре́ча за́втра у́тром." },
    { text: "Это вечер в метро.", ipaHint: "/e/", targetUnitSlugs: ["ru-e", "ru-soft-labials"], focus: "э/е 与软化环境", stressText: "Э́то ве́чер в метро́." },
    { text: "Тётя читает письмо.", ipaHint: "/tʲ tɕ ʲ/", targetUnitSlugs: ["ru-soft-t-d", "ru-ch", "ru-soft-sign"], focus: "软 т/д、ч 和软音符号", stressText: "Тётя чита́ет письмо́." },
    { text: "Зима сегодня холодная.", ipaHint: "/zʲ e x/", targetUnitSlugs: ["ru-soft-s-z", "ru-unstressed-e-ya", "ru-x"], focus: "软 з、非重读 е/я 与 /x/", stressText: "Зима́ сего́дня хо́лодная." },
    { text: "Угол и уголь звучат по-разному.", ipaHint: "/l lʲ/", targetUnitSlugs: ["ru-soft-n-l-r", "ru-soft-sign"], focus: "л/ль 与软音符号改变词义", stressText: "У́гол и у́голь звуча́т по-ра́зному." },
    { text: "Пять билетов лежат на столе.", ipaHint: "/pʲ bʲ/", targetUnitSlugs: ["ru-soft-labials", "ru-final-devoicing"], focus: "唇音软化和词尾清化", stressText: "Пять биле́тов лежа́т на столе́." },
    { text: "Цирк в центре города.", ipaHint: "/ts e/", targetUnitSlugs: ["ru-ts", "ru-e", "ru-unstressed-o-a"], focus: "ц、е/э 和非重读 о", stressText: "Цирк в це́нтре го́рода." },
    { text: "Новый музей рядом с вокзалом.", ipaHint: "/j zʲ assimilation/", targetUnitSlugs: ["ru-j", "ru-soft-s-z", "ru-voicing-assimilation"], focus: "й、软 з 和清浊同化", stressText: "Но́вый музе́й ря́дом с вокза́лом." },
    { text: "Семья едет на юг.", ipaHint: "/ja je ju/", targetUnitSlugs: ["ru-iotated-vowels", "ru-j"], focus: "я/е/ю 的 /j/ 与软化", stressText: "Семья́ е́дет на юг." },
    { text: "Москва и молоко требуют редукции.", ipaHint: "/ɐ ə/", targetUnitSlugs: ["ru-unstressed-o-a", "ru-stress-reduction"], focus: "о/а 弱化和先找重音", stressText: "Москва́ и молоко́ тре́буют реду́кции." },
    { text: "Без тебя и из школы меняется звонкость.", ipaHint: "voicing assimilation", targetUnitSlugs: ["ru-voicing-assimilation", "ru-sh-zh"], focus: "短语里的清浊同化", stressText: "Без тебя́ и из шко́лы меня́ется зво́нкость." },
    { text: "Друг ждёт у гаража.", ipaHint: "final devoicing", targetUnitSlugs: ["ru-final-devoicing", "ru-sh-zh"], focus: "词尾清化和 ж/ш 音色", stressText: "Друг ждёт у гаража́." },
    { text: "Текст сложный, но без лишних гласных.", ipaHint: "clusters", targetUnitSlugs: ["ru-clusters", "ru-voicing-assimilation"], focus: "辅音丛不插入额外元音", stressText: "Текст сло́жный, но без ли́шних гла́сных." },
  ],
};

export function getLanguageLearningDeck(
  languageId: DeckLanguageId,
): LanguageLearningDeck {
  return LANGUAGE_LEARNING_DECKS[languageId];
}
