import { PHONEMES } from "@/lib/phoneme-data";
import type { LanguageId } from "@/types/language";
import type { Difficulty, KeywordEntry, PhonemeCategory, PhonemeData } from "@/types/phoneme";

type UnitInput = {
  languageId: LanguageId;
  slug: string;
  ipa: string;
  symbol?: string;
  name: string;
  category: PhonemeCategory;
  example: string;
  keywords: KeywordEntry[];
  difficulty: Difficulty;
  description: string;
  notes?: string[];
  soundUnitType?: PhonemeData["soundUnitType"];
};

function unit(input: UnitInput): PhonemeData {
  return {
    languageId: input.languageId,
    ipa: input.ipa,
    symbol: input.symbol ?? input.ipa.replaceAll("/", ""),
    slug: input.slug,
    name: input.name,
    category: input.category,
    soundUnitType: input.soundUnitType ?? "phoneme",
    example: input.example,
    keywords: input.keywords,
    difficulty: input.difficulty,
    description: input.description,
    notes: input.notes,
    video: {
      status: "planned",
      label: "待补充授权教学视频",
    },
  };
}

const ENGLISH_PHONEMES: PhonemeData[] = PHONEMES.map((phoneme) => ({
  ...phoneme,
  languageId: "en-US",
  soundUnitType: "phoneme",
  video: {
    localSrc: `/videos/phonemes/${phoneme.slug}.mp4`,
    status: "ready",
    label: "Rachel's English 本地教学视频",
  },
}));

const SPANISH_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "es-ES",
    slug: "es-a",
    ipa: "/a/",
    name: "open central vowel",
    category: "vowel",
    example: "casa",
    keywords: [
      { word: "casa", ipa: "/ˈkasa/" },
      { word: "mano", ipa: "/ˈmano/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "mapa", ipa: "/ˈmapa/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "sal", ipa: "/sal/" },
    ],
    difficulty: "easy",
    description: "嘴巴自然张开，舌位低而居中，保持短、纯、稳定，不滑向英语 /æ/ 或 /ɑː/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-e",
    ipa: "/e/",
    name: "close-mid front vowel",
    category: "vowel",
    example: "mesa",
    keywords: [
      { word: "mesa", ipa: "/ˈmesa/" },
      { word: "leche", ipa: "/ˈletʃe/" },
      { word: "perro", ipa: "/ˈpero/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "tres", ipa: "/tɾes/" },
      { word: "dedo", ipa: "/ˈdeðo/" },
    ],
    difficulty: "easy",
    description: "舌前部抬起，嘴巴半闭；不要读成英语双元音 /eɪ/，结尾不滑。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-i",
    ipa: "/i/",
    name: "close front vowel",
    category: "vowel",
    example: "sí",
    keywords: [
      { word: "sí", ipa: "/si/" },
      { word: "vida", ipa: "/ˈbiða/" },
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "libro", ipa: "/ˈlibɾo/" },
      { word: "cinco", ipa: "/ˈθinko/" },
      { word: "mira", ipa: "/ˈmiɾa/" },
    ],
    difficulty: "easy",
    description: "嘴角微展，舌前高位；声音短而干净，不拖成长英语 /iː/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-o",
    ipa: "/o/",
    name: "close-mid back rounded vowel",
    category: "vowel",
    example: "sol",
    keywords: [
      { word: "sol", ipa: "/sol/" },
      { word: "hola", ipa: "/ˈola/" },
      { word: "coche", ipa: "/ˈkotʃe/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "todo", ipa: "/ˈtoðo/" },
      { word: "boca", ipa: "/ˈboka/" },
    ],
    difficulty: "easy",
    description: "双唇收圆，舌后部抬起；保持单元音，不要滑成英语 /oʊ/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-u",
    ipa: "/u/",
    name: "close back rounded vowel",
    category: "vowel",
    example: "luna",
    keywords: [
      { word: "luna", ipa: "/ˈluna/" },
      { word: "uno", ipa: "/ˈuno/" },
      { word: "tú", ipa: "/tu/" },
      { word: "azul", ipa: "/aˈθul/" },
      { word: "mundo", ipa: "/ˈmundo/" },
      { word: "curso", ipa: "/ˈkuɾso/" },
    ],
    difficulty: "easy",
    description: "双唇收圆但声音短，不要按英语长 /uː/ 拉长。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-bv",
    ipa: "/b ~ β/",
    name: "Spanish b/v stop and approximant",
    category: "consonant",
    soundUnitType: "contrast",
    example: "vida",
    keywords: [
      { word: "vida", ipa: "/ˈbiða/" },
      { word: "vino", ipa: "/ˈbino/" },
      { word: "boca", ipa: "/ˈboka/" },
      { word: "bebé", ipa: "/beˈβe/" },
      { word: "saber", ipa: "/saˈβeɾ/" },
      { word: "uva", ipa: "/ˈuβa/" },
    ],
    difficulty: "high",
    description: "词首或鼻音后更像 /b/；两个元音之间放松成 /β/，双唇接近但不要咬下唇读英语 /v/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-d",
    ipa: "/d ~ ð/",
    name: "Spanish d stop and approximant",
    category: "consonant",
    example: "dedo",
    keywords: [
      { word: "dedo", ipa: "/ˈdeðo/" },
      { word: "día", ipa: "/ˈdia/" },
      { word: "nada", ipa: "/ˈnaða/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "lado", ipa: "/ˈlaðo/" },
      { word: "dos", ipa: "/dos/" },
    ],
    difficulty: "high",
    description: "词首较硬，元音间轻擦化；舌尖靠近上齿背，别读成英语强爆破 /d/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-g",
    ipa: "/g ~ ɣ/",
    name: "Spanish g stop and approximant",
    category: "consonant",
    example: "gato",
    keywords: [
      { word: "gato", ipa: "/ˈgato/" },
      { word: "agua", ipa: "/ˈaɣwa/" },
      { word: "amigo", ipa: "/aˈmiɣo/" },
      { word: "grande", ipa: "/ˈgɾande/" },
      { word: "juego", ipa: "/ˈxweɣo/" },
      { word: "lago", ipa: "/ˈlaɣo/" },
    ],
    difficulty: "medium",
    description: "元音间放松为 /ɣ/，舌后部接近软腭但不完全堵住气流。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-theta",
    ipa: "/θ/",
    name: "Castilian c/z",
    category: "consonant",
    example: "cielo",
    keywords: [
      { word: "cielo", ipa: "/ˈθjelo/" },
      { word: "zapato", ipa: "/θaˈpato/" },
      { word: "cinco", ipa: "/ˈθinko/" },
      { word: "gracias", ipa: "/ˈgɾaθjas/" },
      { word: "luz", ipa: "/luθ/" },
      { word: "azul", ipa: "/aˈθul/" },
    ],
    difficulty: "medium",
    description: "西班牙本土常用；舌尖轻触上下齿间送气。拉美西语常并入 /s/，后续需要做方言开关。",
    notes: ["当前按 es-ES 处理；拉美西语需要单独 profile。"],
  }),
  unit({
    languageId: "es-ES",
    slug: "es-x",
    ipa: "/x/",
    name: "voiceless velar fricative",
    category: "consonant",
    example: "jamón",
    keywords: [
      { word: "jamón", ipa: "/xaˈmon/" },
      { word: "juego", ipa: "/ˈxweɣo/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "gente", ipa: "/ˈxente/" },
      { word: "José", ipa: "/xoˈse/" },
      { word: "México", ipa: "/ˈmexiko/" },
    ],
    difficulty: "high",
    description: "舌后部靠近软腭形成摩擦，像更靠后的“哈”，不要读成英语 /h/。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-ny",
    ipa: "/ɲ/",
    name: "palatal nasal",
    category: "consonant",
    example: "niño",
    keywords: [
      { word: "niño", ipa: "/ˈniɲo/" },
      { word: "año", ipa: "/ˈaɲo/" },
      { word: "señor", ipa: "/seˈɲoɾ/" },
      { word: "mañana", ipa: "/maˈɲana/" },
      { word: "sueño", ipa: "/ˈsweɲo/" },
      { word: "España", ipa: "/esˈpaɲa/" },
    ],
    difficulty: "medium",
    description: "舌面贴近硬腭，鼻音从硬腭位置出来，不要拆成 /n/ + /j/ 两个音。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-tap-r",
    ipa: "/ɾ/",
    name: "single tap r",
    category: "consonant",
    example: "pero",
    keywords: [
      { word: "pero", ipa: "/ˈpeɾo/" },
      { word: "caro", ipa: "/ˈkaɾo/" },
      { word: "para", ipa: "/ˈpaɾa/" },
      { word: "tarde", ipa: "/ˈtaɾðe/" },
      { word: "verde", ipa: "/ˈbeɾðe/" },
      { word: "libro", ipa: "/ˈlibɾo/" },
    ],
    difficulty: "high",
    description: "舌尖快速弹一下上齿龈，只有一次接触，不要读成英语卷舌 r。",
  }),
  unit({
    languageId: "es-ES",
    slug: "es-trill-r",
    ipa: "/r/",
    name: "trilled rr",
    category: "consonant",
    example: "perro",
    keywords: [
      { word: "perro", ipa: "/ˈpero/" },
      { word: "rojo", ipa: "/ˈroxo/" },
      { word: "rápido", ipa: "/ˈrapiðo/" },
      { word: "carro", ipa: "/ˈkaro/" },
      { word: "tierra", ipa: "/ˈtjera/" },
      { word: "río", ipa: "/ˈrio/" },
    ],
    difficulty: "high",
    description: "舌尖在上齿龈处连续颤动；先练稳定气流和舌尖放松，再追求多次颤动。",
  }),
];

const FRENCH_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "fr-FR",
    slug: "fr-i",
    ipa: "/i/",
    name: "close front unrounded vowel",
    category: "vowel",
    example: "si",
    keywords: [
      { word: "si", ipa: "/si/" },
      { word: "ville", ipa: "/vil/" },
      { word: "vite", ipa: "/vit/" },
      { word: "midi", ipa: "/midi/" },
      { word: "ici", ipa: "/isi/" },
      { word: "lit", ipa: "/li/" },
    ],
    difficulty: "easy",
    description: "舌前高位，嘴角微展；短而紧，不按英语 /iː/ 拉长。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-y",
    ipa: "/y/",
    name: "close front rounded vowel",
    category: "vowel",
    example: "tu",
    keywords: [
      { word: "tu", ipa: "/ty/" },
      { word: "lune", ipa: "/lyn/" },
      { word: "rue", ipa: "/ʁy/" },
      { word: "dur", ipa: "/dyʁ/" },
      { word: "musique", ipa: "/myzik/" },
      { word: "sur", ipa: "/syʁ/" },
    ],
    difficulty: "high",
    description: "舌头摆 /i/ 的高前位置，同时双唇像 /u/ 一样收圆；中文学习者很容易退成 /u/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-u",
    ipa: "/u/",
    name: "close back rounded vowel",
    category: "vowel",
    example: "vous",
    keywords: [
      { word: "vous", ipa: "/vu/" },
      { word: "nous", ipa: "/nu/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "jour", ipa: "/ʒuʁ/" },
      { word: "sous", ipa: "/su/" },
      { word: "tout", ipa: "/tu/" },
    ],
    difficulty: "medium",
    description: "双唇收圆，舌后高位；要和 /y/ 分开，/u/ 的舌位更靠后。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e",
    ipa: "/e/",
    name: "close-mid front vowel",
    category: "vowel",
    example: "été",
    keywords: [
      { word: "été", ipa: "/ete/" },
      { word: "nez", ipa: "/ne/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "café", ipa: "/kafe/" },
      { word: "mes", ipa: "/me/" },
      { word: "bébé", ipa: "/bebe/" },
    ],
    difficulty: "medium",
    description: "舌前中高位，声音干净稳定，不滑成英语 /eɪ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e-open",
    ipa: "/ɛ/",
    name: "open-mid front vowel",
    category: "vowel",
    example: "sel",
    keywords: [
      { word: "sel", ipa: "/sɛl/" },
      { word: "mère", ipa: "/mɛʁ/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "belle", ipa: "/bɛl/" },
      { word: "sept", ipa: "/sɛt/" },
      { word: "faire", ipa: "/fɛʁ/" },
    ],
    difficulty: "medium",
    description: "嘴巴比 /e/ 更开，舌前略低；要和 /e/ 做对比训练。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-close",
    ipa: "/ø/",
    name: "close-mid front rounded vowel",
    category: "vowel",
    example: "deux",
    keywords: [
      { word: "deux", ipa: "/dø/" },
      { word: "bleu", ipa: "/blø/" },
      { word: "peu", ipa: "/pø/" },
      { word: "heureux", ipa: "/øʁø/" },
      { word: "feu", ipa: "/fø/" },
      { word: "jeu", ipa: "/ʒø/" },
    ],
    difficulty: "high",
    description: "像 /e/ 的舌位加上圆唇；不要变成 /o/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-open",
    ipa: "/œ/",
    name: "open-mid front rounded vowel",
    category: "vowel",
    example: "sœur",
    keywords: [
      { word: "sœur", ipa: "/sœʁ/" },
      { word: "jeune", ipa: "/ʒœn/" },
      { word: "peur", ipa: "/pœʁ/" },
      { word: "fleur", ipa: "/flœʁ/" },
      { word: "neuf", ipa: "/nœf/" },
      { word: "seul", ipa: "/sœl/" },
    ],
    difficulty: "high",
    description: "像 /ɛ/ 的开口加圆唇；法语圆唇前元音是中国学习者重点难点。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-an",
    ipa: "/ɑ̃/",
    name: "nasal vowel an/en",
    category: "vowel",
    example: "sans",
    keywords: [
      { word: "sans", ipa: "/sɑ̃/" },
      { word: "France", ipa: "/fʁɑ̃s/" },
      { word: "temps", ipa: "/tɑ̃/" },
      { word: "grand", ipa: "/gʁɑ̃/" },
      { word: "dans", ipa: "/dɑ̃/" },
      { word: "maman", ipa: "/mamɑ̃/" },
    ],
    difficulty: "high",
    description: "口腔元音同时打开鼻腔共鸣，不要在后面加清楚的 /n/ 或 /ŋ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-in",
    ipa: "/ɛ̃/",
    name: "nasal vowel in/ain",
    category: "vowel",
    example: "vin",
    keywords: [
      { word: "vin", ipa: "/vɛ̃/" },
      { word: "pain", ipa: "/pɛ̃/" },
      { word: "bien", ipa: "/bjɛ̃/" },
      { word: "matin", ipa: "/matɛ̃/" },
      { word: "cinq", ipa: "/sɛ̃k/" },
      { word: "main", ipa: "/mɛ̃/" },
    ],
    difficulty: "high",
    description: "舌前中低位加鼻化；和 /ɑ̃/、/ɔ̃/ 的口型距离要拉开。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-on",
    ipa: "/ɔ̃/",
    name: "nasal vowel on",
    category: "vowel",
    example: "bon",
    keywords: [
      { word: "bon", ipa: "/bɔ̃/" },
      { word: "nom", ipa: "/nɔ̃/" },
      { word: "son", ipa: "/sɔ̃/" },
      { word: "monde", ipa: "/mɔ̃d/" },
      { word: "bonjour", ipa: "/bɔ̃ʒuʁ/" },
      { word: "long", ipa: "/lɔ̃/" },
    ],
    difficulty: "high",
    description: "圆唇后元音加鼻化；不要读成“ong”的明显尾音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-r",
    ipa: "/ʁ/",
    name: "French uvular r",
    category: "consonant",
    example: "rue",
    keywords: [
      { word: "rue", ipa: "/ʁy/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "Paris", ipa: "/paʁi/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "frère", ipa: "/fʁɛʁ/" },
    ],
    difficulty: "high",
    description: "舌根靠近小舌产生摩擦或近音，不是英语卷舌 r，也不是西语弹舌 r。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-liaison",
    ipa: "/‿/",
    name: "liaison and enchaînement",
    category: "prosody",
    soundUnitType: "prosody",
    example: "les amis",
    keywords: [
      { word: "les amis", ipa: "/lezami/" },
      { word: "un ami", ipa: "/œ̃nami/" },
      { word: "vous avez", ipa: "/vuzave/" },
      { word: "petit ami", ipa: "/pətitami/" },
      { word: "grand homme", ipa: "/gʁɑ̃tɔm/" },
      { word: "chez elle", ipa: "/ʃezɛl/" },
    ],
    difficulty: "high",
    description: "法语词尾辅音常静音，但在连诵环境会重新出现；这是句子层训练，不该当作单个音素评分。",
  }),
];

const RUSSIAN_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "ru-RU",
    slug: "ru-a",
    ipa: "/a/",
    name: "Russian а",
    category: "vowel",
    example: "мама",
    keywords: [
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "да", ipa: "/da/" },
      { word: "там", ipa: "/tam/" },
      { word: "парк", ipa: "/park/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
    ],
    difficulty: "easy",
    description: "重读时清楚开放，非重读时会弱化；俄语元音练习必须带重音位置。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-o",
    ipa: "/o/",
    name: "Russian stressed о",
    category: "vowel",
    example: "дом",
    keywords: [
      { word: "дом", ipa: "/dom/" },
      { word: "кот", ipa: "/kot/" },
      { word: "мост", ipa: "/most/" },
      { word: "нос", ipa: "/nos/" },
      { word: "рот", ipa: "/rot/" },
      { word: "город", ipa: "/ˈgorət/" },
    ],
    difficulty: "medium",
    description: "重读 /o/ 圆唇清楚；非重读 о 通常弱化接近 /a/ 或 /ə/，不能只按字母读。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-i",
    ipa: "/i/",
    name: "Russian и",
    category: "vowel",
    example: "мир",
    keywords: [
      { word: "мир", ipa: "/mir/" },
      { word: "лиса", ipa: "/lʲɪˈsa/" },
      { word: "имя", ipa: "/ˈimʲə/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "синий", ipa: "/ˈsʲinʲɪj/" },
      { word: "пить", ipa: "/pʲitʲ/" },
    ],
    difficulty: "medium",
    description: "常让前面的辅音软化；练这个音时要同时听辅音硬软变化。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-y",
    ipa: "/ɨ/",
    name: "Russian ы",
    category: "vowel",
    example: "мы",
    keywords: [
      { word: "мы", ipa: "/mɨ/" },
      { word: "сыр", ipa: "/sɨr/" },
      { word: "ты", ipa: "/tɨ/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "быстро", ipa: "/ˈbɨstrə/" },
      { word: "сын", ipa: "/sɨn/" },
    ],
    difficulty: "high",
    description: "舌身更靠后更紧，不能读成 /i/；中文学习者需要和 и 成组对比。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-u",
    ipa: "/u/",
    name: "Russian у",
    category: "vowel",
    example: "луна",
    keywords: [
      { word: "луна", ipa: "/lʊˈna/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "утро", ipa: "/ˈutrə/" },
      { word: "музыка", ipa: "/ˈmuzɨkə/" },
      { word: "суп", ipa: "/sup/" },
      { word: "друг", ipa: "/druk/" },
    ],
    difficulty: "medium",
    description: "圆唇高后元音；非重读时会弱化，但仍要保留圆唇趋势。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-hard-soft",
    ipa: "/C ~ Cʲ/",
    name: "hard vs soft consonants",
    category: "consonant",
    soundUnitType: "contrast",
    example: "брат / брать",
    keywords: [
      { word: "брат", ipa: "/brat/" },
      { word: "брать", ipa: "/bratʲ/" },
      { word: "мел", ipa: "/mʲel/" },
      { word: "мэр", ipa: "/mɛr/" },
      { word: "лук", ipa: "/luk/" },
      { word: "люк", ipa: "/lʲuk/" },
    ],
    difficulty: "high",
    description: "俄语不是一个软音，而是成体系的硬/软辅音对；软音时舌面抬向硬腭。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-r",
    ipa: "/r/",
    name: "Russian trilled r",
    category: "consonant",
    example: "река",
    keywords: [
      { word: "река", ipa: "/rʲɪˈka/" },
      { word: "рука", ipa: "/rʊˈka/" },
      { word: "рыба", ipa: "/ˈrɨbə/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "друг", ipa: "/druk/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
    ],
    difficulty: "high",
    description: "舌尖颤音，且有硬 /r/ 与软 /rʲ/ 对比；不能替换成英语卷舌 r。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-x",
    ipa: "/x/",
    name: "Russian х",
    category: "consonant",
    example: "хлеб",
    keywords: [
      { word: "хлеб", ipa: "/xlʲep/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "тихо", ipa: "/ˈtʲixə/" },
      { word: "сахар", ipa: "/ˈsaxər/" },
      { word: "мох", ipa: "/mox/" },
      { word: "холод", ipa: "/ˈxolət/" },
    ],
    difficulty: "medium",
    description: "舌后部靠近软腭摩擦，比英语 /h/ 更靠后、更有摩擦感。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-sh-zh",
    ipa: "/ʂ ʐ/",
    name: "retroflex-like ш/ж",
    category: "consonant",
    soundUnitType: "contrast",
    example: "шум / жук",
    keywords: [
      { word: "шум", ipa: "/ʂum/" },
      { word: "жук", ipa: "/ʐuk/" },
      { word: "школа", ipa: "/ˈʂkolə/" },
      { word: "жена", ipa: "/ʐɨˈna/" },
      { word: "машина", ipa: "/mɐˈʂinə/" },
      { word: "жить", ipa: "/ʐɨtʲ/" },
    ],
    difficulty: "high",
    description: "舌尖/舌叶后缩，音色比英语 /ʃ ʒ/ 更厚；注意 ж 后常接 /ɨ/ 音色。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-ts-ch-shch",
    ipa: "/ts tɕ ɕː/",
    name: "ц/ч/щ affricate and fricative set",
    category: "consonant",
    soundUnitType: "contrast",
    example: "цирк / чай / щи",
    keywords: [
      { word: "цирк", ipa: "/tsɨrk/" },
      { word: "чай", ipa: "/tɕaj/" },
      { word: "щи", ipa: "/ɕːi/" },
      { word: "улица", ipa: "/ˈulʲɪtsə/" },
      { word: "часы", ipa: "/tɕɪˈsɨ/" },
      { word: "площадь", ipa: "/ˈploɕːətʲ/" },
    ],
    difficulty: "high",
    description: "三个音位置和软硬感不同，不能全部用中文“吃/七”近似替代。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-stress-reduction",
    ipa: "/ˈ + ə ɐ/",
    name: "stress and vowel reduction",
    category: "prosody",
    soundUnitType: "prosody",
    example: "молоко",
    keywords: [
      { word: "молоко", ipa: "/məlɐˈko/" },
      { word: "хорошо", ipa: "/xərɐˈʂo/" },
      { word: "город", ipa: "/ˈgorət/" },
      { word: "мама", ipa: "/ˈmamə/" },
      { word: "работа", ipa: "/rɐˈbotə/" },
      { word: "сегодня", ipa: "/sʲɪˈvodnʲə/" },
    ],
    difficulty: "high",
    description: "俄语重音会改变元音质量。这个是句词层训练单位，不应被当成单个音素评分。",
  }),
  unit({
    languageId: "ru-RU",
    slug: "ru-clusters",
    ipa: "/CC(C)/",
    name: "consonant clusters",
    category: "cluster",
    soundUnitType: "cluster",
    example: "встреча",
    keywords: [
      { word: "встреча", ipa: "/ˈfstrʲetɕə/" },
      { word: "здравствуйте", ipa: "/ˈzdrastvʊjtʲe/" },
      { word: "текст", ipa: "/tʲekst/" },
      { word: "спорт", ipa: "/sport/" },
      { word: "взгляд", ipa: "/vzglʲat/" },
      { word: "стол", ipa: "/stol/" },
    ],
    difficulty: "high",
    description: "俄语辅音丛不能自动插入元音；先慢速保留每个辅音，再逐步加速。",
  }),
];

export const LANGUAGE_PHONEMES: Record<LanguageId, PhonemeData[]> = {
  "en-US": ENGLISH_PHONEMES,
  "es-ES": SPANISH_PHONEMES,
  "fr-FR": FRENCH_PHONEMES,
  "ru-RU": RUSSIAN_PHONEMES,
};

export function getLanguagePhonemes(languageId: LanguageId): PhonemeData[] {
  return LANGUAGE_PHONEMES[languageId];
}

export function getLanguagePhonemesByCategory(
  languageId: LanguageId,
  category: PhonemeCategory,
): PhonemeData[] {
  return LANGUAGE_PHONEMES[languageId].filter((phoneme) => phoneme.category === category);
}

export function getLanguagePhonemeBySlug(
  languageId: LanguageId,
  slug: string,
): PhonemeData | undefined {
  return LANGUAGE_PHONEMES[languageId].find((phoneme) => phoneme.slug === slug);
}

export function getAnyLanguagePhonemeBySlug(slug: string): PhonemeData | undefined {
  return Object.values(LANGUAGE_PHONEMES)
    .flat()
    .find((phoneme) => phoneme.slug === slug);
}

export function getAllLanguagePhonemeSlugs(): string[] {
  return Object.values(LANGUAGE_PHONEMES)
    .flat()
    .map((phoneme) => phoneme.slug);
}

export function hasLocalPhonemeAssets(phoneme: PhonemeData): boolean {
  return phoneme.languageId === "en-US";
}
