import type { PhonemeData } from "@/types/phoneme";
import { unit } from "@/lib/language-sound-units/utils";

export const FRENCH_PHONEMES: PhonemeData[] = [
  unit({
    languageId: "fr-FR",
    slug: "fr-i",
    ipa: "/i/",
    name: "close front unrounded vowel",
    category: "vowel",
    example: "si",
    keywords: [
      { word: "si", ipa: "/si/" },
      { word: "ville", ipa: "/vil/" },
      { word: "vite", ipa: "/vit/" },
      { word: "midi", ipa: "/midi/" },
      { word: "ici", ipa: "/isi/" },
      { word: "lit", ipa: "/li/" },
    ],
    difficulty: "easy",
    description: "舌前高位，嘴角微展；短而紧，不按英语 /iː/ 拉长。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-y",
    ipa: "/y/",
    name: "close front rounded vowel",
    category: "vowel",
    example: "tu",
    keywords: [
      { word: "tu", ipa: "/ty/" },
      { word: "lune", ipa: "/lyn/" },
      { word: "rue", ipa: "/ʁy/" },
      { word: "dur", ipa: "/dyʁ/" },
      { word: "musique", ipa: "/myzik/" },
      { word: "sur", ipa: "/syʁ/" },
    ],
    difficulty: "high",
    description:
      "舌头摆 /i/ 的高前位置，同时双唇像 /u/ 一样收圆；中文学习者很容易退成 /u/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-u",
    ipa: "/u/",
    name: "close back rounded vowel",
    category: "vowel",
    example: "vous",
    keywords: [
      { word: "vous", ipa: "/vu/" },
      { word: "nous", ipa: "/nu/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "jour", ipa: "/ʒuʁ/" },
      { word: "sous", ipa: "/su/" },
      { word: "tout", ipa: "/tu/" },
    ],
    difficulty: "medium",
    description: "双唇收圆，舌后高位；要和 /y/ 分开，/u/ 的舌位更靠后。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e",
    ipa: "/e/",
    name: "close-mid front vowel",
    category: "vowel",
    example: "été",
    keywords: [
      { word: "été", ipa: "/ete/" },
      { word: "nez", ipa: "/ne/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "café", ipa: "/kafe/" },
      { word: "mes", ipa: "/me/" },
      { word: "bébé", ipa: "/bebe/" },
    ],
    difficulty: "medium",
    description: "舌前中高位，声音干净稳定，不滑成英语 /eɪ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-e-open",
    ipa: "/ɛ/",
    name: "open-mid front vowel",
    category: "vowel",
    example: "sel",
    keywords: [
      { word: "sel", ipa: "/sɛl/" },
      { word: "mère", ipa: "/mɛʁ/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "belle", ipa: "/bɛl/" },
      { word: "sept", ipa: "/sɛt/" },
      { word: "faire", ipa: "/fɛʁ/" },
    ],
    difficulty: "medium",
    description: "嘴巴比 /e/ 更开，舌前略低；要和 /e/ 做对比训练。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-close",
    ipa: "/ø/",
    name: "close-mid front rounded vowel",
    category: "vowel",
    example: "deux",
    keywords: [
      { word: "deux", ipa: "/dø/" },
      { word: "bleu", ipa: "/blø/" },
      { word: "peu", ipa: "/pø/" },
      { word: "heureux", ipa: "/øʁø/" },
      { word: "feu", ipa: "/fø/" },
      { word: "jeu", ipa: "/ʒø/" },
    ],
    difficulty: "high",
    description: "像 /e/ 的舌位加上圆唇；不要变成 /o/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-eu-open",
    ipa: "/œ/",
    name: "open-mid front rounded vowel",
    category: "vowel",
    example: "sœur",
    keywords: [
      { word: "sœur", ipa: "/sœʁ/" },
      { word: "jeune", ipa: "/ʒœn/" },
      { word: "peur", ipa: "/pœʁ/" },
      { word: "fleur", ipa: "/flœʁ/" },
      { word: "neuf", ipa: "/nœf/" },
      { word: "seul", ipa: "/sœl/" },
    ],
    difficulty: "high",
    description: "像 /ɛ/ 的开口加圆唇；法语圆唇前元音是中国学习者重点难点。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-an",
    ipa: "/ɑ̃/",
    name: "nasal vowel an/en",
    category: "vowel",
    example: "sans",
    keywords: [
      { word: "sans", ipa: "/sɑ̃/" },
      { word: "France", ipa: "/fʁɑ̃s/" },
      { word: "temps", ipa: "/tɑ̃/" },
      { word: "grand", ipa: "/gʁɑ̃/" },
      { word: "dans", ipa: "/dɑ̃/" },
      { word: "maman", ipa: "/mamɑ̃/" },
    ],
    difficulty: "high",
    description: "口腔元音同时打开鼻腔共鸣，不要在后面加清楚的 /n/ 或 /ŋ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-in",
    ipa: "/ɛ̃/",
    name: "nasal vowel in/ain",
    category: "vowel",
    example: "vin",
    keywords: [
      { word: "vin", ipa: "/vɛ̃/" },
      { word: "pain", ipa: "/pɛ̃/" },
      { word: "bien", ipa: "/bjɛ̃/" },
      { word: "matin", ipa: "/matɛ̃/" },
      { word: "cinq", ipa: "/sɛ̃k/" },
      { word: "main", ipa: "/mɛ̃/" },
    ],
    difficulty: "high",
    description: "舌前中低位加鼻化；和 /ɑ̃/、/ɔ̃/ 的口型距离要拉开。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-on",
    ipa: "/ɔ̃/",
    name: "nasal vowel on",
    category: "vowel",
    example: "bon",
    keywords: [
      { word: "bon", ipa: "/bɔ̃/" },
      { word: "nom", ipa: "/nɔ̃/" },
      { word: "son", ipa: "/sɔ̃/" },
      { word: "monde", ipa: "/mɔ̃d/" },
      { word: "bonjour", ipa: "/bɔ̃ʒuʁ/" },
      { word: "long", ipa: "/lɔ̃/" },
    ],
    difficulty: "high",
    description: "圆唇后元音加鼻化；不要读成“ong”的明显尾音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-r",
    ipa: "/ʁ/",
    name: "French uvular r",
    category: "consonant",
    example: "rue",
    keywords: [
      { word: "rue", ipa: "/ʁy/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "Paris", ipa: "/paʁi/" },
      { word: "merci", ipa: "/mɛʁsi/" },
      { word: "très", ipa: "/tʁɛ/" },
      { word: "frère", ipa: "/fʁɛʁ/" },
    ],
    difficulty: "high",
    description:
      "舌根靠近小舌产生摩擦或近音，不是英语卷舌 r，也不是西语弹舌 r。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-liaison",
    ipa: "/‿/",
    name: "liaison and enchaînement",
    category: "prosody",
    soundUnitType: "prosody",
    example: "les amis",
    keywords: [
      { word: "les amis", ipa: "/lezami/" },
      { word: "un ami", ipa: "/œ̃nami/" },
      { word: "vous avez", ipa: "/vuzave/" },
      { word: "petit ami", ipa: "/pətitami/" },
      { word: "grand homme", ipa: "/gʁɑ̃tɔm/" },
      { word: "chez elle", ipa: "/ʃezɛl/" },
    ],
    difficulty: "high",
    description:
      "法语词尾辅音常静音，但在连诵环境会重新出现；这是句子层训练，不该当作单个音素评分。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-a",
    ipa: "/a/",
    name: "open front vowel",
    category: "vowel",
    example: "la",
    keywords: [
      { word: "la", ipa: "/la/" },
      { word: "ma", ipa: "/ma/" },
      { word: "chat", ipa: "/ʃa/" },
      { word: "ami", ipa: "/ami/" },
      { word: "Paris", ipa: "/paʁi/" },
      { word: "table", ipa: "/tabl/" },
      { word: "madame", ipa: "/madam/" },
      { word: "salade", ipa: "/salad/" },
      { word: "classe", ipa: "/klas/" },
      { word: "arrive", ipa: "/aʁiv/" },
      { word: "avec", ipa: "/avɛk/" },
      { word: "animal", ipa: "/animal/" },
      { word: "samedi", ipa: "/samdi/" },
      { word: "matin", ipa: "/matɛ̃/" },
      { word: "facile", ipa: "/fasil/" },
      { word: "baguette", ipa: "/bagɛt/" },
      { word: "jardin", ipa: "/ʒaʁdɛ̃/" },
      { word: "la table", ipa: "/la tabl/" },
      { word: "Paris arrive", ipa: "/paʁi aʁiv/" },
      { word: "un ami", ipa: "/œ̃nami/" },
    ],
    difficulty: "easy",
    description:
      "嘴巴打开，舌位偏前；不要像英语 /æ/ 那样拉扯，也不要拖成双元音。",
    notes: ["现代标准法语常把 /a/ 与后元音 /ɑ/ 合并；本模块先按核心 /a/ 训练。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-schwa",
    ipa: "/ə/",
    name: "French schwa / e caduc",
    category: "vowel",
    soundUnitType: "prosody",
    example: "petit",
    keywords: [
      { word: "je", ipa: "/ʒə/" },
      { word: "le", ipa: "/lə/" },
      { word: "de", ipa: "/də/" },
      { word: "petit", ipa: "/pəti/" },
      { word: "demain", ipa: "/dəmɛ̃/" },
      { word: "demander", ipa: "/dəmɑ̃de/" },
      { word: "menu", ipa: "/məny/" },
      { word: "cheveux", ipa: "/ʃəvø/" },
      { word: "semaine", ipa: "/səmɛn/" },
      { word: "samedi", ipa: "/samdi/" },
      { word: "fenêtre", ipa: "/fənɛtʁ/" },
      { word: "revenez", ipa: "/ʁəvəne/" },
      { word: "premier", ipa: "/pʁəmje/" },
      { word: "petite", ipa: "/pətit/" },
      { word: "ce matin", ipa: "/sə matɛ̃/" },
      { word: "je veux", ipa: "/ʒə vø/" },
      { word: "le petit", ipa: "/lə pəti/" },
      { word: "de demain", ipa: "/də dəmɛ̃/" },
      { word: "menu du jour", ipa: "/məny dy ʒuʁ/" },
      { word: "revenez samedi", ipa: "/ʁəvəne samedi/" },
    ],
    difficulty: "high",
    description:
      "法语 e caduc /ə/ 在慢速和教学读法中可听见，在自然语流里可能弱化或省略。",
    notes: [
      "不要把 /ə/ 读成英语重读 /ɜː/；它短、轻、可变。",
      "schwa 是否出现受语速、地区和语境影响，应作为语流规则训练。",
    ],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-o-close",
    ipa: "/o/",
    name: "close-mid back rounded vowel",
    category: "vowel",
    example: "beau",
    keywords: [
      { word: "beau", ipa: "/bo/" },
      { word: "eau", ipa: "/o/" },
      { word: "mot", ipa: "/mo/" },
      { word: "dos", ipa: "/do/" },
      { word: "trop", ipa: "/tʁo/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "rose", ipa: "/ʁoz/" },
      { word: "gauche", ipa: "/goʃ/" },
      { word: "photo", ipa: "/foto/" },
      { word: "vélo", ipa: "/velo/" },
      { word: "bureau", ipa: "/byʁo/" },
      { word: "cadeau", ipa: "/kado/" },
      { word: "bateau", ipa: "/bato/" },
      { word: "zéro", ipa: "/zeʁo/" },
      { word: "hôtel", ipa: "/otɛl/" },
      { word: "drôle", ipa: "/dʁol/" },
      { word: "jaune", ipa: "/ʒon/" },
      { word: "beau vélo", ipa: "/bo velo/" },
      { word: "eau chaude", ipa: "/o ʃod/" },
      { word: "un cadeau", ipa: "/œ̃ kado/" },
    ],
    difficulty: "medium",
    description:
      "圆唇、舌后中高位；不要读成英语 /oʊ/ 双元音，结尾不滑。",
    notes: ["常见拼写 eau/au/o 可对应 /o/，但开闭受词和地区影响，需词典复核。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-o-open",
    ipa: "/ɔ/",
    name: "open-mid back rounded vowel",
    category: "vowel",
    example: "porte",
    keywords: [
      { word: "porte", ipa: "/pɔʁt/" },
      { word: "école", ipa: "/ekɔl/" },
      { word: "homme", ipa: "/ɔm/" },
      { word: "comme", ipa: "/kɔm/" },
      { word: "bonne", ipa: "/bɔn/" },
      { word: "fort", ipa: "/fɔʁ/" },
      { word: "encore", ipa: "/ɑ̃kɔʁ/" },
      { word: "corps", ipa: "/kɔʁ/" },
      { word: "sort", ipa: "/sɔʁ/" },
      { word: "note", ipa: "/nɔt/" },
      { word: "ordinateur", ipa: "/ɔʁdinatœʁ/" },
      { word: "d'accord", ipa: "/dakɔʁ/" },
      { word: "pomme", ipa: "/pɔm/" },
      { word: "bol", ipa: "/bɔl/" },
      { word: "colle", ipa: "/kɔl/" },
      { word: "folle", ipa: "/fɔl/" },
      { word: "octobre", ipa: "/ɔktɔbʁ/" },
      { word: "bonne porte", ipa: "/bɔn pɔʁt/" },
      { word: "encore fort", ipa: "/ɑ̃kɔʁ fɔʁ/" },
      { word: "pomme comme ça", ipa: "/pɔm kɔm sa/" },
    ],
    difficulty: "medium",
    description:
      "圆唇但口腔更开；和 /o/ 做 beau/bonne、eau/homme 式对比。",
    notes: ["闭音节中常出现 /ɔ/，但不能只靠拼写猜，要用词典或 IPA 资源复核。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-un",
    ipa: "/œ̃/",
    name: "nasal front rounded vowel un",
    category: "vowel",
    soundUnitType: "contrast",
    example: "un",
    keywords: [
      { word: "un", ipa: "/œ̃/" },
      { word: "brun", ipa: "/bʁœ̃/" },
      { word: "parfum", ipa: "/paʁfœ̃/" },
      { word: "lundi", ipa: "/lœ̃di/" },
      { word: "emprunt", ipa: "/ɑ̃pʁœ̃/" },
      { word: "commun", ipa: "/kɔmœ̃/" },
      { word: "quelqu'un", ipa: "/kɛlkœ̃/" },
      { word: "chacun", ipa: "/ʃakœ̃/" },
      { word: "aucun", ipa: "/okœ̃/" },
      { word: "jeun", ipa: "/ʒœ̃/" },
      { word: "défunt", ipa: "/defœ̃/" },
      { word: "humble", ipa: "/œ̃bl/" },
      { word: "un lundi", ipa: "/œ̃ lœ̃di/" },
      { word: "brun parfum", ipa: "/bʁœ̃ paʁfœ̃/" },
      { word: "aucun emprunt", ipa: "/okœ̃ ɑ̃pʁœ̃/" },
      { word: "quelqu'un vient", ipa: "/kɛlkœ̃ vjɛ̃/" },
      { word: "parfum brun", ipa: "/paʁfœ̃ bʁœ̃/" },
      { word: "lundi matin", ipa: "/lœ̃di matɛ̃/" },
      { word: "un commun", ipa: "/œ̃ kɔmœ̃/" },
      { word: "chacun parle", ipa: "/ʃakœ̃ paʁl/" },
    ],
    difficulty: "high",
    description:
      "传统 IPA 表里单列 /œ̃/；许多现代法语口音会和 /ɛ̃/ 合并，学习时先知道这个变体。",
    notes: [
      "现代巴黎法语常把 /œ̃/ merge/合并到 /ɛ̃/；评分和反馈不应把合并口音直接判错。",
      "先作为听辨和变体提示，再进入精细发音训练。",
    ],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-sh",
    ipa: "/ʃ/",
    name: "French ch",
    category: "consonant",
    example: "chat",
    keywords: [
      { word: "chat", ipa: "/ʃa/" },
      { word: "chez", ipa: "/ʃe/" },
      { word: "chose", ipa: "/ʃoz/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "machine", ipa: "/maʃin/" },
      { word: "dimanche", ipa: "/dimɑ̃ʃ/" },
      { word: "chercher", ipa: "/ʃɛʁʃe/" },
      { word: "chemise", ipa: "/ʃəmiz/" },
      { word: "chanson", ipa: "/ʃɑ̃sɔ̃/" },
      { word: "bouche", ipa: "/buʃ/" },
      { word: "gauche", ipa: "/goʃ/" },
      { word: "marché", ipa: "/maʁʃe/" },
      { word: "chemin", ipa: "/ʃəmɛ̃/" },
      { word: "chambre", ipa: "/ʃɑ̃bʁ/" },
      { word: "chapeau", ipa: "/ʃapo/" },
      { word: "chaise", ipa: "/ʃɛz/" },
      { word: "chaque", ipa: "/ʃak/" },
      { word: "chez elle", ipa: "/ʃezɛl/" },
      { word: "chat chaud", ipa: "/ʃa ʃo/" },
      { word: "chercher chez nous", ipa: "/ʃɛʁʃe ʃe nu/" },
    ],
    difficulty: "medium",
    description: "法语 ch 是纯摩擦 /ʃ/，不要读成英语或西语式 /tʃ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-zh",
    ipa: "/ʒ/",
    name: "French j/soft g",
    category: "consonant",
    example: "je",
    keywords: [
      { word: "je", ipa: "/ʒə/" },
      { word: "jour", ipa: "/ʒuʁ/" },
      { word: "jamais", ipa: "/ʒamɛ/" },
      { word: "rouge", ipa: "/ʁuʒ/" },
      { word: "manger", ipa: "/mɑ̃ʒe/" },
      { word: "jardin", ipa: "/ʒaʁdɛ̃/" },
      { word: "déjeuner", ipa: "/deʒœne/" },
      { word: "général", ipa: "/ʒeneʁal/" },
      { word: "jupe", ipa: "/ʒyp/" },
      { word: "juste", ipa: "/ʒyst/" },
      { word: "image", ipa: "/imaʒ/" },
      { word: "fromage", ipa: "/fʁɔmaʒ/" },
      { word: "garage", ipa: "/gaʁaʒ/" },
      { word: "gentil", ipa: "/ʒɑ̃ti/" },
      { word: "journal", ipa: "/ʒuʁnal/" },
      { word: "gilet", ipa: "/ʒilɛ/" },
      { word: "je joue", ipa: "/ʒə ʒu/" },
      { word: "jour rouge", ipa: "/ʒuʁ ʁuʒ/" },
      { word: "jardin joli", ipa: "/ʒaʁdɛ̃ ʒɔli/" },
      { word: "manger du fromage", ipa: "/mɑ̃ʒe dy fʁɔmaʒ/" },
    ],
    difficulty: "medium",
    description: "声带振动的 /ʒ/，像 /ʃ/ 的浊音版本；不要读成 /dʒ/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-ny",
    ipa: "/ɲ/",
    name: "French gn",
    category: "consonant",
    example: "vigne",
    keywords: [
      { word: "vigne", ipa: "/viɲ/" },
      { word: "montagne", ipa: "/mɔ̃taɲ/" },
      { word: "oignon", ipa: "/ɔɲɔ̃/" },
      { word: "signature", ipa: "/siɲatyʁ/" },
      { word: "campagne", ipa: "/kɑ̃paɲ/" },
      { word: "ligne", ipa: "/liɲ/" },
      { word: "peigne", ipa: "/pɛɲ/" },
      { word: "agneau", ipa: "/aɲo/" },
      { word: "Espagne", ipa: "/ɛspaɲ/" },
      { word: "Bretagne", ipa: "/bʁətaɲ/" },
      { word: "gagner", ipa: "/gaɲe/" },
      { word: "enseigner", ipa: "/ɑ̃sɛɲe/" },
      { word: "mignon", ipa: "/miɲɔ̃/" },
      { word: "ignorer", ipa: "/iɲɔʁe/" },
      { word: "signe", ipa: "/siɲ/" },
      { word: "digne", ipa: "/diɲ/" },
      { word: "ligne droite", ipa: "/liɲ dʁwat/" },
      { word: "vigne rouge", ipa: "/viɲ ʁuʒ/" },
      { word: "montagne blanche", ipa: "/mɔ̃taɲ blɑ̃ʃ/" },
      { word: "mignon agneau", ipa: "/miɲɔ̃ aɲo/" },
    ],
    difficulty: "medium",
    description: "gn 常对应 /ɲ/；舌面贴近硬腭发鼻音，不要拆成 /n/ + /j/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-glide-j",
    ipa: "/j/",
    name: "French yod glide",
    category: "consonant",
    soundUnitType: "contrast",
    example: "fille",
    keywords: [
      { word: "fille", ipa: "/fij/" },
      { word: "famille", ipa: "/famij/" },
      { word: "bien", ipa: "/bjɛ̃/" },
      { word: "pied", ipa: "/pje/" },
      { word: "hier", ipa: "/jɛʁ/" },
      { word: "yeux", ipa: "/jø/" },
      { word: "payer", ipa: "/peje/" },
      { word: "voyage", ipa: "/vwajaʒ/" },
      { word: "soleil", ipa: "/sɔlɛj/" },
      { word: "travail", ipa: "/tʁavaj/" },
      { word: "oreille", ipa: "/ɔʁɛj/" },
      { word: "conseil", ipa: "/kɔ̃sɛj/" },
      { word: "meilleur", ipa: "/mɛjœʁ/" },
      { word: "juillet", ipa: "/ʒɥijɛ/" },
      { word: "février", ipa: "/fevʁije/" },
      { word: "Parisien", ipa: "/paʁizjɛ̃/" },
      { word: "bien joué", ipa: "/bjɛ̃ ʒwe/" },
      { word: "ma famille", ipa: "/ma famij/" },
      { word: "payer hier", ipa: "/peje jɛʁ/" },
      { word: "voyage au soleil", ipa: "/vwajaʒ o sɔlɛj/" },
    ],
    difficulty: "medium",
    description: "法语 /j/ 是很短的前滑音；不要额外加一个完整元音。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-glide-hui",
    ipa: "/ɥ/",
    name: "French front rounded glide",
    category: "consonant",
    soundUnitType: "contrast",
    example: "huit",
    keywords: [
      { word: "huit", ipa: "/ɥit/" },
      { word: "huile", ipa: "/ɥil/" },
      { word: "huis", ipa: "/ɥi/" },
      { word: "huître", ipa: "/ɥitʁ/" },
      { word: "nuit", ipa: "/nɥi/" },
      { word: "pluie", ipa: "/plɥi/" },
      { word: "suisse", ipa: "/sɥis/" },
      { word: "suivre", ipa: "/sɥivʁ/" },
      { word: "aiguille", ipa: "/egɥij/" },
      { word: "aigu", ipa: "/egy/" },
      { word: "nuire", ipa: "/nɥiʁ/" },
      { word: "lui", ipa: "/lɥi/" },
      { word: "depuis", ipa: "/dəpɥi/" },
      { word: "aujourd'hui", ipa: "/oʒuʁdɥi/" },
      { word: "juin", ipa: "/ʒɥɛ̃/" },
      { word: "Louis", ipa: "/lwi/" },
      { word: "huit nuits", ipa: "/ɥit nɥi/" },
      { word: "pluie suisse", ipa: "/plɥi sɥis/" },
      { word: "depuis juin", ipa: "/dəpɥi ʒɥɛ̃/" },
      { word: "lui aussi", ipa: "/lɥi osi/" },
    ],
    difficulty: "high",
    description:
      "/ɥ/ 是 /y/ 的短滑音：舌位偏前、双唇收圆，不要退成英语 /w/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-glide-w",
    ipa: "/w/",
    name: "French back rounded glide",
    category: "consonant",
    soundUnitType: "contrast",
    example: "oui",
    keywords: [
      { word: "oui", ipa: "/wi/" },
      { word: "ouest", ipa: "/wɛst/" },
      { word: "oiseau", ipa: "/wazo/" },
      { word: "quoi", ipa: "/kwa/" },
      { word: "moi", ipa: "/mwa/" },
      { word: "toi", ipa: "/twa/" },
      { word: "trois", ipa: "/tʁwa/" },
      { word: "boire", ipa: "/bwaʁ/" },
      { word: "voir", ipa: "/vwaʁ/" },
      { word: "pouvoir", ipa: "/puvwaʁ/" },
      { word: "croire", ipa: "/kʁwaʁ/" },
      { word: "noir", ipa: "/nwaʁ/" },
      { word: "soir", ipa: "/swaʁ/" },
      { word: "voiture", ipa: "/vwatyʁ/" },
      { word: "loi", ipa: "/lwa/" },
      { word: "loin", ipa: "/lwɛ̃/" },
      { word: "oui trois", ipa: "/wi tʁwa/" },
      { word: "moi et toi", ipa: "/mwa e twa/" },
      { word: "voir l'oiseau", ipa: "/vwaʁ lwazo/" },
      { word: "soir noir", ipa: "/swaʁ nwaʁ/" },
    ],
    difficulty: "medium",
    description: "/w/ 是短后圆唇滑音；和前圆唇 /ɥ/ 分开，避免把 lui 读成 /lwi/。",
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-final-consonant-silence",
    ipa: "silent final C",
    name: "silent final consonants",
    category: "prosody",
    soundUnitType: "prosody",
    example: "petit",
    keywords: [
      { word: "petit", ipa: "/pəti/" },
      { word: "grand", ipa: "/gʁɑ̃/" },
      { word: "trop", ipa: "/tʁo/" },
      { word: "beaucoup", ipa: "/boku/" },
      { word: "nez", ipa: "/ne/" },
      { word: "dos", ipa: "/do/" },
      { word: "chaud", ipa: "/ʃo/" },
      { word: "froid", ipa: "/fʁwa/" },
      { word: "temps", ipa: "/tɑ̃/" },
      { word: "long", ipa: "/lɔ̃/" },
      { word: "blanc", ipa: "/blɑ̃/" },
      { word: "vert", ipa: "/vɛʁ/" },
      { word: "parler", ipa: "/paʁle/" },
      { word: "fin", ipa: "/fɛ̃/" },
      { word: "pied", ipa: "/pje/" },
      { word: "mot", ipa: "/mo/" },
      { word: "un petit chat", ipa: "/œ̃ pəti ʃa/" },
      { word: "grand froid", ipa: "/gʁɑ̃ fʁwa/" },
      { word: "beaucoup trop", ipa: "/boku tʁo/" },
      { word: "temps chaud", ipa: "/tɑ̃ ʃo/" },
    ],
    difficulty: "high",
    description:
      "许多法语词尾辅音孤立时不发音；不要按拼写把 t/d/p/s/x/z 全部读出来。",
    notes: ["这是 phrase-level 规则：liaison 或派生形式里词尾辅音可能重新出现。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-enchainement",
    ipa: "enchaînement",
    name: "enchaînement",
    category: "prosody",
    soundUnitType: "prosody",
    example: "il arrive",
    keywords: [
      { word: "il arrive", ipa: "/ilaʁiv/" },
      { word: "elle arrive", ipa: "/ɛlaʁiv/" },
      { word: "avec elle", ipa: "/avɛkɛl/" },
      { word: "il habite", ipa: "/ilabit/" },
      { word: "elle aime", ipa: "/ɛlɛm/" },
      { word: "un homme", ipa: "/œ̃nɔm/" },
      { word: "mon ami", ipa: "/mɔnami/" },
      { word: "bonne idée", ipa: "/bɔnidɛ/" },
      { word: "petite école", ipa: "/pətitekɔl/" },
      { word: "grande amie", ipa: "/gʁɑ̃dami/" },
      { word: "dans une", ipa: "/dɑ̃zyn/" },
      { word: "chez elle", ipa: "/ʃezɛl/" },
      { word: "la porte ouverte", ipa: "/la pɔʁtuvɛʁt/" },
      { word: "le livre est", ipa: "/lə livʁɛ/" },
      { word: "une robe orange", ipa: "/yn ʁɔbɔʁɑ̃ʒ/" },
      { word: "il est ici", ipa: "/ilɛtisi/" },
      { word: "Paris arrive", ipa: "/paʁi aʁiv/" },
      { word: "Luc arrive", ipa: "/lykaʁiv/" },
      { word: "elle ouvre", ipa: "/ɛluvʁ/" },
      { word: "avec un ami", ipa: "/avɛkœ̃nami/" },
    ],
    difficulty: "high",
    description:
      "本来发音的词尾辅音会自然连到下一个元音开头词；这不是新增音素，而是语流连接。",
    notes: ["和 liaison 不同，enchaînement 中词尾辅音本来就发音，只是跨词连接。"],
  }),
  unit({
    languageId: "fr-FR",
    slug: "fr-elision",
    ipa: "elision",
    name: "elision",
    category: "prosody",
    soundUnitType: "prosody",
    example: "j'aime",
    keywords: [
      { word: "j'aime", ipa: "/ʒɛm/" },
      { word: "j'habite", ipa: "/ʒabit/" },
      { word: "l'ami", ipa: "/lami/" },
      { word: "l'école", ipa: "/lekɔl/" },
      { word: "c'est", ipa: "/sɛ/" },
      { word: "d'accord", ipa: "/dakɔʁ/" },
      { word: "qu'il", ipa: "/kil/" },
      { word: "qu'elle", ipa: "/kɛl/" },
      { word: "jusqu'à", ipa: "/ʒyska/" },
      { word: "n'est-ce pas", ipa: "/nɛs pa/" },
      { word: "l'homme", ipa: "/lɔm/" },
      { word: "l'eau", ipa: "/lo/" },
      { word: "j'écoute", ipa: "/ʒekut/" },
      { word: "j'arrive", ipa: "/ʒaʁiv/" },
      { word: "c'était", ipa: "/setɛ/" },
      { word: "d'ici", ipa: "/disi/" },
      { word: "j'aime Paris", ipa: "/ʒɛm paʁi/" },
      { word: "l'ami arrive", ipa: "/lami aʁiv/" },
      { word: "c'est ouvert", ipa: "/sɛ uvɛʁ/" },
      { word: "d'accord avec elle", ipa: "/dakɔʁ avɛkɛl/" },
    ],
    difficulty: "high",
    description:
      "法语在元音前常省略弱元音并用撇号连接；按词逐个读会破坏自然语流。",
    notes: ["elision 是拼写和发音共同发生的 phrase-level 现象，应和单词孤立发音分开评分。"],
  }),
];
